ssh test-sentry sudo systemctl stop bandd yoda
ssh test-validator3 sudo systemctl stop bandd yoda
ssh test-validator4 sudo systemctl stop bandd yoda
ssh test-validator5 sudo systemctl stop bandd yoda
ssh test-validator6 sudo systemctl stop bandd yoda
ssh test-validator7 sudo systemctl stop bandd yoda
ssh test-validator8 sudo systemctl stop bandd yoda
ssh test-validator9 sudo systemctl stop bandd yoda
ssh test-validator10 sudo systemctl stop bandd yoda
ssh test-validator11 sudo systemctl stop bandd yoda
ssh test-validator12 sudo systemctl stop bandd yoda
ssh test-validator13 sudo systemctl stop bandd yoda
ssh test-validator14 sudo systemctl stop bandd yoda
ssh test-validator15 sudo systemctl stop bandd yoda
ssh test-validator16 sudo systemctl stop bandd yoda
ssh test-firer sudo systemctl stop bandd yoda