#!/usr/bin/env python3
from websocket import create_connection
import json
import requests
import sys

SOCKET_URL = "wss://ws-feed.pro.coinbase.com"


def check_complete(dict, symbols):
    for symbol in symbols:
        if dict[symbol] == None:
            return False
    return True


def main(symbols):
    ws = create_connection("wss://ws-feed.pro.coinbase.com")
    socket_open_message = {
        "type": "subscribe",
        "product_ids": symbols,
        "channels": ["ticker"],
    }
    socket_open = json.dumps(socket_open_message)
    ws.send(socket_open)
    prices = dict.fromkeys(symbols)
    while check_complete(prices, symbols) == False:
        result = json.loads(ws.recv())
        if "product_id" in result:
            prices[result["product_id"]] = result["price"]
    return ",".join(
        [px for symbol in symbols for (key, px) in prices.items() if symbol == key]
    )


if __name__ == "__main__":
    try:
        print(main([(s + "-USD") for s in [*sys.argv[1:]]]))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
