#!/usr/bin/env python3
import requests
import sys

URL = "https://jzjsymorj3.execute-api.ap-southeast-1.amazonaws.com/live/CMC/{}"


def adjust_rounding(data):
    if data < 1:
        return round(data, 8)
    elif data < 10:
        return round(data, 6)
    else:
        return round(data, 4)


def main(symbols):
    try:
        symbols_str = ",".join(symbols)
        coins = requests.get(URL.format(symbols_str)).json()["result"]["data"]
        return ",".join(
            [
                str(adjust_rounding(data["quote"]["USD"]["price"]))
                for symbol in symbols
                for (sym, data) in coins.items()
                if sym == symbol.upper()
            ]
        )
    except Exception as e:
        print(e)


if __name__ == "__main__":
    try:
        print(main([*sys.argv[1:]]))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
