#!/usr/bin/env python3
import ccxt
import requests
import sys


def gdac(base_symbol, quote_symbol):
    session = requests.session()
    result = session.get(
        f"https://partner.gdac.com/v0.4/public/orderbook?pair={base_symbol}%2F{quote_symbol}",
        timeout=4,
    ).json()
    askprice = float(result["ask"][0]["price"])
    bidprice = float(result["bid"][0]["price"])

    return f"{askprice},{bidprice}"


def main(base_symbol, quote_symbol):
    return gdac(base_symbol, quote_symbol)


if __name__ == "__main__":
    try:
        print(main(*sys.argv[1:]))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
