#!/usr/bin/env python3
import requests
import sys
import time

URL = "https://asia-southeast2-price-caching.cloudfunctions.net/query-price"
headers = {
    "Content-Type": "application/json",
}


def get_price_map():
    data = (
        '{"query":"query temp {\\n assets{\\n symbol\\n token\\n prices{\\n priceAt(timestamp: %d)\\n }\\n\\t}\\n}"}'
        % (int(time.time()) * 1000)
    )
    response = requests.post("https://graph.mirror.finance/graphql", headers=headers, data=data)
    response.raise_for_status()
    assets = response.json()["data"]["assets"]
    price_map = dict()
    for asset in assets:
        price_map[asset["symbol"]] = asset["prices"]["priceAt"]
    return price_map


def main(symbols):
    price_map = get_price_map()
    return ",".join(price for symbol in symbols for (map_symbol, price) in price_map.items() if symbol == map_symbol)


if __name__ == "__main__":
    try:
        print(main(sys.argv[1:]))
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(1)
