#!/usr/bin/env python3
import requests
import sys

URL = "https://min-api.cryptocompare.com/data/pricemulti"


def main(symbols):
    res = requests.get(URL, params={"fsyms": symbols, "tsyms": "USD"})
    return ",".join([str(px["USD"]) for px in list(res.json().values())])


if __name__ == "__main__":
    try:
        print(main(",".join([*sys.argv[1:]])))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
