#!/usr/bin/env python3
import requests
import sys


def gopax(base_symbol, quote_symbol):
    session = requests.session()
    result = session.get(f"https://api.gopax.co.kr/trading-pairs/{base_symbol}-{quote_symbol}/book", timeout=4).json()
    askprice = float(result["ask"][0][1])
    bidprice = float(result["bid"][0][1])

    return f"{askprice},{bidprice}"


def main(base_symbol, quote_symbol):
    return gopax(base_symbol, quote_symbol)


if __name__ == "__main__":
    try:
        print(main(*sys.argv[1:]))
    except Exception as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
